# Generated by Django 2.2.4 on 2021-03-20 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_auto_20210320_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='old_dojo', max_length=255),
            preserve_default=False,
        ),
    ]
