# Generated by Django 2.2.4 on 2021-03-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_dojo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
