# Generated by Django 2.2.4 on 2021-03-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_auto_20210320_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
